[Feature] support keep intermediate container for multi-stage build caching
drone-plugins/drone-docker pull request #368
Opened 2022-06-09 14:59 UTC by zjc17

fore using `--rm=true` makes trouble for multiple stage build. The `always remove intermediate container` behavior prevents people to speed up their building.

Here is the screenshot when --rm=true.
<img width="975" alt="image" src="https://user-images.githubusercontent.com/32964977/172878436-7d2db052-276e-4d9a-9498-14346d45deee.png">

And it should be cached as it's built in jenkins

<img width="761" alt="image" src="https://user-images.githubusercontent.com/32964977/172878637-31015992-1316-4da9-945b-6ed39195e5a6.png">

2022-06-09 15:36 UTC, zjc17 commented
I've tested it ...
<img width="855" alt="image" src="https://user-images.githubusercontent.com/32964977/172887230-35797bf7-1285-40fa-895a-fc03f762f66d.png">

2022-06-14 16:38 UTC, tphoney requested changes
Hey @zjc17 i really like the idea of this feature, with one small proviso. 
There is already the purge command, does it overlap with what you suggest ?https://github.com/drone-plugins/drone-docker/pull/368/files#diff-60e9b6677b8d8d34db5104f9d30dc207928396046b5e06cc9f808508435775bcL232-L237

2022-06-15 05:18 UTC, zjc17 commented
@tphoney cool! It works for me. Thx

2022-06-15 05:19 UTC, closed without merging

2022-06-15 09:26 UTC, tphoney commented
glad i could help shout out to @bradrydzewski for the tip